# Generated by Django 5.2 on 2025-04-07 16:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/media')),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('following', 'Siguiendolo/a'), ('reading', 'Leyendolo/a'), ('watched', 'Visto/a'), ('upcoming', 'Pendiente de Salida'), ('pending_purchase', 'Pendiente de Compra'), ('playing', 'Jugándolo/a'), ('finished', 'Terminado/a')], max_length=20)),
                ('category', models.CharField(choices=[('serie', 'Serie'), ('film', 'Pelicula'), ('novel', 'Novela'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Juego')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('add_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/note')),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='MemorialApp.medium')),
            ],
        ),
    ]
