# Generated by Django 5.2 on 2025-04-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemorialApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='category',
            field=models.CharField(choices=[('serie', 'Serie'), ('film', 'Pelicula'), ('novel', 'Novela'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Juego')], max_length=10),
        ),
    ]
