# Generated by Django 5.1.7 on 2025-03-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
