# Generated by Django 5.2 on 2025-04-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemorialApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='begin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha inicio'),
        ),
    ]
