# Generated by Django 5.2 on 2025-07-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MemorialApp', '0002_alter_medium_title'),
        ('MemorialApp', '0003_alter_medium_title'),
    ]

    operations = [
    ]
