# Generated by Django 5.2 on 2025-07-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MemorialApp', '0004_merge_0002_alter_medium_title_0003_alter_medium_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_fa_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_fa_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
